### ISSUE TITLE
Add authorisation method and region explicitly to settings?

### ISSUE THREAD

**Issue by asimonw** [emfoundation/asset-manager#173]
[Here](http://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html) they say:

> To ensure you use AWS Signature Version 4 it is recommended to set this to the host of your bucket. See the S3 region list to figure out the appropriate endpoint for your bucket. Also be sure to add S3_USE_SIGV4 = True to settings.py

We could investigate the (security) benefits of adding something like:
```python
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_REGION_NAME = 'us-east-1'
```
or
```python
S3_USE_SIGV4 = True
AWS_S3_REGION_NAME = 'us-east-1'
```

**Comment by MertonL** [comment]
Adding to this as I have also encountered issues regarding AWS Sig 4.

If the environment variables are specified as above, when initiating a boto3 client instance, `region_name=settings.AWS_S3_REGION_NAME` should be passed as a parameter so that boto3 does not use the default config file (if set) in the `.aws` folder.
