### ISSUE TITLE
All insights on cello library that are links to websites do not work...

### ISSUE THREAD

**Issue by Kimberley-Heath** [emfoundation/asset-manager#207]
Nick just pointed out that if you try to open an insight on cello that is supposed to be a link to a website you get an error message, whereas if you open an insight which is a PDF it will open correctly.... Not sure if this is a DAM issue or a cello issue... Help! @georgemillard @asimonw

**Comment by asimonw** [comment]
@Kimberley-Heath it's a cello issue. I also only spotted it yesterday. It's been a bug since we moved the library to the DAM, but the bug is definitely a cello bug.

An issue for it was already raised here and will be worked on this week: https://github.com/emfoundation/ce100-app/issues/1268

Closing this one, but thanks for flagging it!
