### ISSUE TITLE
Every Asset has a Format Field

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#236]
Decide on Format list, add a mandatory Format field to every Asset and assign Format to existing Assets.

**Comment by MertonL** [comment]
The current list of agreed format types are:

- Image
- Video 
- Presentation
- Web Link
- Audio 
- Document

**Comment by MertonL** [comment]
I'm capturing Colins suggestions from the Survey on Format Type here:
> Many of our learning resources are multimedia, so how would we categorise them? (e.g. a PDF which contains links to videos, which are integral to the resource). Could **multimedia** be added as a format type?
>
> Also, what would we do about linking to online courses we run? Would they be on the DAM, too? If so, they will need their own format type - **course**.

**Comment by georgemillard** [comment]
Hi Mert,

I think we need to keep a really clear boundary between format and content type. Format is the format of the file (or link if it is one). It should not have an opinion on what the file contains or how it is used. So a pdf is a pdf (in this case document). For me multimedia provides less clarity.

Course could be interesting - but is it a single asset? For me course is more content type than format. So perhaps a course would have format: web link, content type: course.

Would be good to get your thoughts @asimonw

**Comment by asimonw** [comment]
@georgemillard @MertonL I agree that we should keep format and content type clearly separated. Course is not a format and indeed probably not a single asset. In fact, if we just link to it from the DAM it will just be a web link, and the content type will indicate that it's a T&L resource (if that's what we end up calling it).

If we ever host courses on the DAM, then they will consist of many assets, each of them being a video or document, etc.

A PDF with links to other things (like videos) in it should have format Document, because that's what it is. The content type should capture further context.

I think we might be trying to make this layer of the DAM do too many things. It's a digital asset manager, not a content manager. The content management should be a layer on top of this. Keeping that in mind might help us to keep both format and content type focussed. If we want to build a clear and well-structured interface on top of this, we need to start from a very clear and focused foundation. I'm sure you agree with that @georgemillard :)

**Comment by georgemillard** [comment]
Agreed, as a guiding principle, rather than a strict rule, the data should not "care" or know how it is used, and the asset manager should simply and cleanly capture enough data to enable it to be used in a variety of ways.

**Comment by asimonw** [comment]
@georgemillard As this is now on staging, it can be tested an closed.

**Comment by fannyBkane** [comment]
@asimonw @georgemillard lgtm, would be great to now edit the format field for the assets.

**Comment by georgemillard** [comment]
I've updated the format fields for assets on staging. It was done programmatically so may not be perfect but should save us some manual work.

**Comment by fannyBkane** [comment]
@georgemillard @asimonw LGTM :)
