### ISSUE TITLE
Add file format icon description/keyword

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/asset-manager#275]
The asset format icons are not always enough by themselves to let the user know the asset format. A simple solution for now would be to add a keyword for each. 

This applies to the list page and the asset page.

@Fanny to advise @MertonL on design/copy.

**Comment by fannyBkane** [comment]
Ho @MertonL to see the specs please go on [Figma](https://www.figma.com/file/tC08PiIYYrjcFi4y7Qb1CC/MVP-Desktop-V.3)
![screen shot 2018-04-03 at 15 51 43](https://user-images.githubusercontent.com/20577339/38256815-0e896c6a-3757-11e8-8e8a-d48cb32b3d12.png)
![screen shot 2018-04-03 at 15 51 33](https://user-images.githubusercontent.com/20577339/38256810-0d069732-3757-11e8-9622-19ee2d4f4edd.png)

**Comment by asimonw** [comment]
@fannyBkane FYI, these are the display names used:
Image
Video
Presentation
Web link
Audio
Document
Other

Just mentioning it, because some words are a bit longer, so might fit a bit less well underneath the icon. Not sure why we chose 'Web link' over 'Link' though...

**Comment by fannyBkane** [comment]
Thanks for reiterating the names - it should be ok, at least it works on the mockup, so we'll see on staging. @MertonL by the way, the 'keywords' only show on desktop, the mobile stay as it is.

> Just mentioning it, because some words are a bit longer, so might fit a bit less well underneath the icon. Not sure why we chose 'Web link' over 'Link' though...

Could it be changed or shall we backlog it?

**Comment by asimonw** [comment]
@MertonL "Other" is really only there to make sure there is always a value. It's not really supposed to be used indeed, but if someone forgets to select a format, things won't break.

We could use any of the existing formats as a default instead, but I'd say that the downside of that is that it won't be clear whether that format was chosen intentionally or just because it's the default and the uploader forgot to set it. So, by regularly checking whether there are no assets with format other, we have a mechanism for keeping the data correct.

**Comment by fannyBkane** [comment]
@MertonL thanks for raising that. 'other' exists for those assets for which we haven't defined a content type yet. As we curate more assets, that content type list is likely to evolve - something I've pointed out to @MollyM42
![screen shot 2018-04-04 at 14 14 16](https://user-images.githubusercontent.com/20577339/38309726-9e85f890-3812-11e8-80d6-f3a04154fbb7.png)

**Comment by asimonw** [comment]
@georgemillard This has been merged into develop. I'll leave the `awaiting review` label until you've put it on staging, before changing it to `please test`.

**Comment by fannyBkane** [comment]
Hey @MertonL the list looks pretty dense, what about creating more space? 
- Drop the font-size to 0.7 rem (under that it becomes real hard to see words)
- Decrease space between icons+text of list items (by more or less 4px)  or increase space between columns by the same amount, so that there is more space between list items, that will make them look more grouped (when you squint, you should be able to icon+text as one chunk).
![screen shot 2018-04-06 at 09 39 37](https://user-images.githubusercontent.com/20577339/38411398-ec538354-397e-11e8-9f87-c28a0e09f92e.png)

**Comment by MertonL** [comment]
Cheers @fannyBkane, will update the spacing :)

**Comment by fannyBkane** [comment]
@MertonL cheers!

**Comment by asimonw** [comment]
@MertonL If you plan to change the grid spacing used by Bulma, let's have a chat first, because that will affect other pages as well ;)

**Comment by MertonL** [comment]
@asimonw Changed the way I originally implemented the format text, which meant I didn't have to change the core grid - only inner padding & margins
